### ISSUE TITLE
History plugin does not create history.txt

### ISSUE THREAD

**Issue by SanskritFritz** [kokoko3k/higgins#8]
Hence the search history is not searched.
I don't see any errors in the terminal output.

**Comment by kokoko3k** [comment]
Thanks for the report(s) I'll have a chance to take a look in september :)

**Comment by SanskritFritz** [comment]
I really like the design of Higgins, maybe it will replace Kupfer on my desktop!

**Comment by SanskritFritz** [comment]
Actually the history plugin doesn't seem to work at all, since it is at the first place in the plugins list, but no previously started applications appear first when I type the first letter.

**Comment by kokoko3k** [comment]
Hi there.
The history plugin is meant to search for previously selected "documents", and indeed I verified it does create history.txt when you select a document.
I've just updated Its misleading description, sorry about the trouble.

**Comment by SanskritFritz** [comment]
I see, thanks for the clarification. Indeed opening a document creates the history.txt file and it's working the way you described it... well almost, the history element is /home/sans/Documents/2022.pdf but entering only / does not show that element although one character should be enough, right?

**Comment by kokoko3k** [comment]
It seems 2 characters is the minimum (i can't remember where i've put that limit right now, sorry.)

**Comment by SanskritFritz** [comment]
You're right, sorry, two chars do trigger the history.

https://github.com/kokoko3k/higgins/blob/6c29601ec9d4a38703a57b55119e6953e5fe1019/.src/plugins/plugin_009_history.class#L23

This one I guess.
