### ISSUE TITLE
Quit doesn't really quit

### ISSUE THREAD

**Issue by SanskritFritz** [kokoko3k/higgins#9]
When I click on Quit in the context menu, only the xbindkeys_higgins process ends, the gbr3 process remains in memory and the tray icon is still visible. I have to kill the gbr3 process in order to be able to start higgins again.

**Comment by kokoko3k** [comment]
I verified and reproduced the bug.
The cause is the trayicon component that don't exit, and it is an upstream/gambas bug.
I worked around it by forcing the quitting of the application.
It will complain on the terminal about some resourced not freed on exit.
